### ISSUE TITLE
syntax/compilation error in full_sim.ts

### ISSUE THREAD

**Issue by ditchfieldcaleb** [code-423n4/2021-11-fei#3]
Unable to run the simulation due to the following error; using node v12.21.0

```
caleb@CORUSCANT:~/2021-11-fei$ npx hardhat test test/full_sim.ts
No need to generate any newer typings.
An unexpected error occurred:

/home/caleb/2021-11-fei/test/full_sim.ts:35
        await contracts.tribeRagequit?.requery();
                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module.m._compile (/home/caleb/2021-11-fei/node_modules/ts-node/src/index.ts:1371:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .ts] (/home/caleb/2021-11-fei/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/caleb/2021-11-fei/node_modules/mocha/lib/mocha.js:349:36
```

**Comment by ditchfieldcaleb** [comment]
Closing, works with node v14.
